# Generated by Django 5.1.1 on 2025-02-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='newproductmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
