# Generated by Django 5.1.1 on 2025-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_newproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproductmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
