# Generated by Django 5.1.1 on 2025-02-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_newproductmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproductmodel',
            old_name='image',
            new_name='imagepic',
        ),
    ]
