# Generated by Django 5.1.1 on 2025-02-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_image_newproductmodel_imagepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproductmodel',
            old_name='imagepic',
            new_name='image',
        ),
    ]
