# Generated by Django 5.1.1 on 2025-02-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_image_newproductmodel_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproductmodel',
            old_name='image1',
            new_name='image',
        ),
    ]
