# Generated by Django 5.1.1 on 2025-02-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_image1_newproductmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproductmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
