# Generated by Django 5.1.1 on 2025-03-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
