# Generated by Django 5.1.1 on 2025-03-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproductmodel',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registermodel'),
        ),
    ]
