# Generated by Django 5.1.1 on 2025-03-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_newproductmodel_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproductmodel',
            old_name='seller',
            new_name='userid',
        ),
    ]
