# Generated by Django 5.1.1 on 2025-03-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_seller_newproductmodel_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
