# Generated by Django 5.1.1 on 2025-03-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='refurbishedproductmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='photos')),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registermodel')),
            ],
        ),
    ]
