# Generated by Django 5.1.1 on 2025-03-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_refurbishedproductmodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refurbishedproductmodel',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'NotAvailable')], max_length=1),
        ),
    ]
