# Generated by Django 5.1.1 on 2025-03-21 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_refurbishedproductmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='rproductid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.refurbishedproductmodel'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.newproductmodel'),
        ),
        migrations.AlterField(
            model_name='refurbishedproductmodel',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'UnAvailable')], max_length=1),
        ),
    ]
