# Generated by Django 5.1.1 on 2025-03-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
