# Generated by Django 5.1.1 on 2025-03-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalamount',
            field=models.FloatField(null=True),
        ),
    ]
