# Generated by Django 5.1.1 on 2025-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_cart_totalamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refurbishedproductmodel',
            name='status',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
