# Generated by Django 5.1.1 on 2025-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_refurbishedproductmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refurbishedproductmodel',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
