# Generated by Django 5.1.1 on 2025-04-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registermodel'),
        ),
    ]
