# Generated by Django 5.1.1 on 2025-04-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_contact_us_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='pid',
        ),
    ]
