# Generated by Django 5.0.6 on 2025-04-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_contact_us_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=models.BigIntegerField(max_length=10, null=True),
        ),
    ]
