# Generated by Django 5.0.6 on 2025-04-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_registermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
